Update rhods-disconnected-install-helper.yml

diff --git a/.github/workflows/rhods-disconnected-install-helper.yml b/.github/workflows/rhods-disconnected-install-helper.yml
--- a/.github/workflows/rhods-disconnected-install-helper.yml
+++ b/.github/workflows/rhods-disconnected-install-helper.yml
@@ -18,13 +18,16 @@ jobs:
     - name: Validate branch name format
       run: |     
         rhoai_branch="${{ github.event.inputs.branch_name }}"
-        
-        # Check if branch name follows "rhoai-<number>.<number>" format
-        if [[ "$rhoai_branch" =~ ^rhoai-[0-9]+\.[0-9]+$ ]]; then
-          echo "✅ Valid format: $rhoai_branch"
+        if [[ -z "$rhoai_branch" ]]; then
+          echo "⚠️ No branch name provided. Skipping validation..."
         else
-          echo "❌ Invalid format! Expected rhoai-x.y (e.g., rhoai-2.18) but found $rhoai_branch"
-          exit 1
+          # Check if branch name follows "rhoai-<number>.<number>" format
+          if [[ "$rhoai_branch" =~ ^rhoai-[0-9]+\.[0-9]+$ ]]; then
+            echo "✅ Valid format: $rhoai_branch"
+          else
+            echo "❌ Invalid format! Expected rhoai-x.y (e.g., rhoai-2.18) but found $rhoai_branch"
+            exit 1
+          fi
         fi
         shell: bash
     - name: Run rhoai-disconnected-helper.sh script
